#!/usr/bin/env python3
"""Generate immutable checkpoint ROMs and integer golden vectors.

Use --data to evaluate the full public test split. This command does not train,
calibrate, or change quantization. PyTorch is used only to enumerate the existing
frozen float32 nonlinear definition. The project is self-contained: no sibling
software tree is required. Existing PTQ results are verification references only.
"""

import argparse
import json
import math
from pathlib import Path
import time

import numpy as np

from integer_model import EXPORT, GENERATED, LAYERS, MODEL, ROOT, IntegerModel, file_hash, metrics


def piecewise(value, knots, function_name):
    """Pinned operation order of the checkpoint's torch-float32 PWL definition."""
    import torch
    from torch.nn import functional as functional
    boundaries = value.new_tensor(knots)
    ordinates = functional.silu(boundaries) if function_name == "silu" else torch.exp(boundaries)
    indices = torch.bucketize(value.detach().contiguous(), boundaries) - 1
    indices = indices.clamp(0, len(knots) - 2)
    x0 = boundaries[indices]
    x1 = boundaries[indices + 1]
    y0 = ordinates[indices]
    y1 = ordinates[indices + 1]
    result = y0 + (value - x0) * (y1 - y0) / (x1 - x0)
    if function_name == "silu":
        result = torch.where(value < -7.0, torch.zeros_like(value), result)
        result = torch.where(value > 7.0, value, result)
    else:
        result = torch.where(value < -4.0, torch.zeros_like(value), result)
        result = torch.where(value > 1.0, torch.full_like(value, math.e), result)
    return result


def make_tables(export):
    import torch
    torch.set_num_threads(2)
    profile = json.loads((export / "quantization.json").read_text())
    manifest = json.loads((export / "manifest.json").read_text())
    knots = profile["pwlKnots"]
    for key, manifest_key, count, endpoints in [
            ("silu_knots", "siluKnots", 18, (-7.0, 7.0)),
            ("exp_knots", "expKnots", 12, (-4.0, 1.0))]:
        values = knots[key]
        if values != profile["modelConfig"][key] or values != manifest["piecewiseApproximation"][manifest_key]:
            raise ValueError("Frozen PWL knot definitions disagree: " + key)
        if len(values) != count or (values[0], values[-1]) != endpoints or not all(
                np.isfinite(value) for value in values) or not all(a < b for a, b in zip(values, values[1:])):
            raise ValueError("Invalid frozen PWL knots: " + key)
    tables = []
    definitions = []
    for block in range(2):
        for source, target, operation in [("conv", "x", "silu"), ("gateInput", "gate", "silu"), ("expInput", "Abar", "exp")]:
            prefix = "blocks.%d." % block
            input_exp = int(profile["nodes"][prefix + source]["exponent"])
            output_exp = int(profile["nodes"][prefix + target]["exponent"])
            inputs = torch.arange(-128, 128, dtype=torch.float32) * (2.0 ** input_exp)
            values = piecewise(inputs, knots[operation + "_knots"], operation)
            integer = torch.round(values / (2.0 ** output_exp)).clamp(-128, 127).to(torch.int8)
            tables.append(integer.numpy())
            definitions.append({"block": block, "input": prefix + source, "output": prefix + target,
                                "operation": operation, "inputExponent": input_exp, "outputExponent": output_exp})
    return np.stack(tables), {"backend": "torch " + torch.__version__, "dtype": "float32",
                             "definition": "reference/generate.py:piecewise (frozen checkpoint operation order)",
                             "pwlKnots": knots, "addressOrder": "signed inputs -128 through 127", "tables": definitions}


def bsv_rom(name, signature, choices, width):
    lines = ["function Int#(8) " + name + "(" + signature + ");", "\tInt#(8) result = 0;"]
    for condition, address_name, entries in choices:
        lines.append("\tif ( " + condition + " ) begin")
        lines.append("\t\tcase ( " + address_name + " )")
        for address, value in entries:
            if value:
                lines.append("\t\t\t%d'd%d: result = %d;" % (width, address, value))
        lines.extend(["\t\t\tdefault: result = 0;", "\t\tendcase", "\tend"])
    lines.extend(["\treturn result;", "endfunction", ""])
    return lines


def bsv_integer_function(name, signature, variable, values):
    lines = ["function Integer " + name + "(" + signature + ");", "\tInteger result = 0;"]
    for key, value in values:
        literal = json.dumps(key) if isinstance(key, str) else str(key)
        lines.append("\tif ( " + variable + " == " + literal + " ) result = " + str(value) + ";")
    return lines + ["\treturn result;", "endfunction", ""]


def write_bsv(model):
    lines = ["// Generated by reference/generate.py from the verified SW INT8 export.",
             "// First baseline: fixed combinational case lookups; no registered coefficient ROM.",
             "package SwayParameters;", ""]
    banks = []
    biases = []
    for layer, (output, input_name, weight_name, bias_name) in enumerate(LAYERS):
        weight = model.parameters[weight_name]
        for lane in range(4):
            entries = []
            for group in range((len(weight) + 3) // 4):
                row = group * 4 + lane
                for column in range(weight.shape[1]):
                    entries.append((group * weight.shape[1] + column, int(weight[row, column]) if row < len(weight) else 0))
            banks.append(("layerId == %d && lane == %d" % (layer, lane), "addr", entries))
        if bias_name:
            biases.append(("layerId == %d" % layer, "row", list(enumerate(model.parameters[bias_name].tolist()))))
    lines += bsv_rom("linearWeight", "Integer layerId, Integer lane, Bit#(13) addr", banks, 13)
    lines += bsv_rom("linearBias", "Integer layerId, Bit#(9) row", biases, 9)
    for function, index in [("layerInputScale", 1), ("layerWeightScale", 2), ("layerOutputScale", 0)]:
        lines += bsv_integer_function(function, "Integer layerId", "layerId", [(layer, model.exponent(names[index])) for layer, names in enumerate(LAYERS)])
    lines += bsv_integer_function("layerBiasScale", "Integer layerId", "layerId", [(layer, model.exponent(names[3]) if names[3] else 0) for layer, names in enumerate(LAYERS)])
    lines += ["function Bool layerHasBias(Integer layerId);", "\tBool result = False;"]
    for layer, names in enumerate(LAYERS):
        if names[3]:
            lines.append("\tif ( layerId == %d ) result = True;" % layer)
    lines += ["\treturn result;", "endfunction", ""]
    lines += bsv_integer_function("nodeScale", "String name", "name", [(name, node["exponent"]) for name, node in model.profile["nodes"].items()])
    lines += ["function Integer blockScale(Integer blockId, String suffix);", "\tInteger result = 0;"]
    for block in range(2):
        lines.append("\tif ( blockId == %d ) begin" % block)
        prefix = "blocks.%d." % block
        for name, node in model.profile["nodes"].items():
            if name.startswith(prefix):
                lines.append("\t\tif ( suffix == %s ) result = %d;" % (json.dumps(name[len(prefix):]), node["exponent"]))
        lines.append("\tend")
    lines += ["\treturn result;", "endfunction", ""]
    for function, parameter in [("normWeight", "normWeight"), ("normBias", "normBias"), ("convBias", "convBias"), ("directD", "D")]:
        choices = [("blockId == %d" % block, "channel", list(enumerate(model.parameters["blocks.%d.%s" % (block, parameter)].tolist()))) for block in range(2)]
        lines += bsv_rom(function, "Integer blockId, Bit#(6) channel", choices, 6)
    choices = []
    for block in range(2):
        for tap in range(4):
            choices.append(("blockId == %d && tap == %d" % (block, tap), "channel", list(enumerate(model.parameters["blocks.%d.convWeight" % block][:, 0, tap].tolist()))))
    lines += bsv_rom("convWeight", "Integer blockId, Integer tap, Bit#(6) channel", choices, 6)
    choices = []
    for block in range(2):
        for state in range(8):
            choices.append(("blockId == %d && n == %d" % (block, state), "channel", list(enumerate(model.parameters["blocks.%d.A" % block][:, state].tolist()))))
    lines += bsv_rom("stateA", "Integer blockId, Integer n, Bit#(6) channel", choices, 6)
    choices = [("tableId == %d" % table, "pack(inputValue)", [((value & 255), int(model.tables[table, value + 128])) for value in range(-128, 128)]) for table in range(6)]
    lines += bsv_rom("nonlinearLookup", "Integer tableId, Int#(8) inputValue", choices, 8)
    lines += ["endpackage", ""]
    (GENERATED / "SwayParameters.bsv").write_text("\n".join(lines))


def write_hex(path, values):
    Path(path).write_text("".join("%02x\n" % (int(value) & 255) for value in np.asarray(values).reshape(-1)))


def finalize_report(report):
    deliverables = ["SwayParameters.bsv", "nonlinear_tables.npy", "GeneratedTestConfig.bsv", "test_input.hex",
                    "test_expected.hex", "test_trace.npz", "predictions_integer.npy"]
    report["generatedSHA256"] = {name: file_hash(GENERATED / name) for name in deliverables if (GENERATED / name).is_file()}
    report["referenceSHA256"] = {name: file_hash(Path(__file__).parent / name) for name in ["integer_model.py", "generate.py"]}
    (GENERATED / "reference_report.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")


def verify_model_bundle(export):
    import torch
    provenance = json.loads((MODEL / "provenance.json").read_text())
    for name, digest in provenance["filesSHA256"].items():
        if file_hash(MODEL / name) != digest:
            raise ValueError("Frozen model file changed: " + name)
    checkpoint = torch.load(MODEL / "checkpoint.pt", map_location="cpu", weights_only=False)
    if checkpoint.get("quantization_method") != "PTQ" or "qat" in checkpoint.get("training_mode", "").lower():
        raise ValueError("Expected the selected non-QAT PTQ checkpoint")
    profile = json.loads((export / "quantization.json").read_text())
    if profile != checkpoint["ptq_profile"]:
        raise ValueError("Export does not use the checkpoint's frozen PTQ profile")
    manifest = json.loads((export / "manifest.json").read_text())
    if manifest["modelConfig"] != checkpoint["config"]:
        raise ValueError("Export configuration differs from frozen checkpoint")
    for entry in manifest["tensors"]:
        actual = np.frombuffer((export / entry["binary"]).read_bytes(), dtype=np.int8).reshape(entry["shape"])
        expected = checkpoint["int8_parameters"][entry["parameterName"]].numpy()
        if not np.array_equal(actual, expected):
            raise ValueError("INT8 export differs from checkpoint: " + entry["parameterName"])
    return provenance


def hardware_width_checks(model):
    """Conservative full-INT8-domain bounds for the first baseline datapath."""
    checks = []
    def bounded(name, magnitude, bits, signed=True):
        limit = (1 << (bits - 1 if signed else bits)) - 1
        if magnitude > limit:
            raise OverflowError("Baseline arithmetic width exceeded: " + name)
        checks.append({"operation": name, "maximumAbsoluteValue": int(magnitude), "bits": bits, "signed": signed})
    def aligned_bound(magnitude, source, target):
        shift = source - target
        if abs(shift) >= 63:
            raise OverflowError("Baseline rescale shift exceeds INT64")
        return magnitude << shift if shift >= 0 else (magnitude + (1 << -shift) - 1) >> -shift
    for layer, (output, input_name, weight_name, bias_name) in enumerate(LAYERS):
        weight = model.parameters[weight_name]
        bound = int(np.max(np.sum(np.abs(weight), axis=1))) * 128
        bounded("linear%d accumulation" % layer, bound, 32)
        exponent = model.exponent(input_name) + model.exponent(weight_name)
        common = min(exponent, model.exponent(bias_name)) if bias_name else exponent
        bound = aligned_bound(bound, exponent, common)
        if bias_name:
            bound += aligned_bound(int(np.abs(model.parameters[bias_name]).max()), model.exponent(bias_name), common)
        bounded("linear%d aligned bias" % layer, bound, 64)
        bounded("linear%d output rescale" % layer, aligned_bound(bound, common, model.exponent(output)), 64)
    for block in range(2):
        prefix = "blocks.%d." % block
        exp = lambda name: model.exponent(prefix + name)
        common = min(exp("normWeight"), exp("normBias"), exp("norm"))
        weight_shift, bias_shift, output_shift = [exp(name) - common for name in ["normWeight", "normBias", "norm"]]
        if weight_shift > 10 or bias_shift > 10 or output_shift > 18:
            raise OverflowError("Baseline divider alignment unsupported")
        bounded(prefix + "norm numerator", (4845 * 128 << weight_shift) + (5100 * 128 << bias_shift), 32)
        bounded(prefix + "norm denominator", 5100 << output_shift, 32, False)
        convolution_bound = int(np.abs(model.parameters[prefix + "convWeight"]).sum(axis=-1).max()) * 128
        bounded(prefix + "convolution sum", convolution_bound, 18)
        common = min(exp("convInput") + exp("convWeight"), exp("convBias"))
        convolution_bound = aligned_bound(convolution_bound, exp("convInput") + exp("convWeight"), common)
        convolution_bound += aligned_bound(int(np.abs(model.parameters[prefix + "convBias"]).max()), exp("convBias"), common)
        bounded(prefix + "convolution aligned bias", convolution_bound, 64)
        bounded(prefix + "convolution output rescale", aligned_bound(convolution_bound, common, exp("conv")), 64)
        drive_bound = aligned_bound(128 * 128, exp("Bbar") + exp("x"), exp("currentState"))
        bounded(prefix + "recurrent and drive", 128 * (1 << 16) + drive_bound, 64)
        state_output = (1 << 23) * 128 * 8
        bounded(prefix + "state reduction", state_output, 35)
        common = min(exp("currentState") + exp("C"), exp("x") + exp("D"))
        output_bound = aligned_bound(state_output, exp("currentState") + exp("C"), common)
        output_bound += aligned_bound(128 * 128, exp("x") + exp("D"), common)
        bounded(prefix + "SSM aligned output", output_bound, 64)
        bounded(prefix + "SSM output rescale", aligned_bound(output_bound, common, exp("ssmY")), 64)
        for source, target in [("in", "convInput"), ("in", "gateInput"),
                               ("xProjection", "deltaInput"), ("xProjection", "B"),
                               ("xProjection", "C"), ("deltaProjection", "delta")]:
            bounded(prefix + source + " to " + target, aligned_bound(128, exp(source), exp(target)), 64)
        for left, right, target in [("delta", "A", "expInput"), ("delta", "B", "Bbar"),
                                    ("ssmY", "gate", "gated")]:
            bounded(prefix + target + " product rescale", aligned_bound(128 * 128, exp(left) + exp(right), exp(target)), 64)
        input_exp = model.exponent("embedding" if block == 0 else "blocks.0.residual")
        common = min(input_exp, exp("out"))
        residual_bound = aligned_bound(128, input_exp, common) + aligned_bound(128, exp("out"), common)
        bounded(prefix + "residual aligned sum", residual_bound, 64)
        bounded(prefix + "residual output rescale", aligned_bound(residual_bound, common, exp("residual")), 64)
    for source, target in [("input", "patches"), ("blocks.1.residual", "headInput"), ("headHidden", "headActivation")]:
        bounded(source + " to " + target, aligned_bound(128, model.exponent(source), model.exponent(target)), 64)
    return checks


def arithmetic_checks(model):
    from integer_model import divide_even, rescale
    numerators = np.arange(-65536, 65537, dtype=np.int64)
    for denominator in [1, 2, 3, 7, 16, 20, 255, 5100, 81600]:
        expected = np.rint(numerators.astype(np.float64) / denominator).astype(np.int64)
        if not np.array_equal(divide_even(numerators, denominator), expected):
            raise AssertionError("Signed ties-even division mismatch")
    for shift in range(-16, 17):
        expected = np.rint(numerators.astype(np.float64) * (2.0 ** shift)).astype(np.int64)
        if not np.array_equal(rescale(numerators, shift, 0), expected):
            raise AssertionError("Signed ties-even shift mismatch")
    for block in range(2):
        for constant in [-128, -1, 0, 1, 127]:
            value = np.full((1, 1, 20), constant, dtype=np.int64)
            prefix = "blocks.%d" % block
            from integer_model import requantize
            expected = requantize(model.parameters[prefix + ".normBias"], model.exponent(prefix + ".normBias"), model.exponent(prefix + ".norm"))
            if not np.array_equal(model.normalization(value, prefix)[0, 0], expected):
                raise AssertionError("Constant range normalization mismatch")
    return {"signedDivision": "1179657 numerator/divisor cases passed", "signedRescale": "4325409 value/shift cases passed", "constantNormalization": "10 cases passed"}


def write_fixtures(model, provenance):
    features = np.load(MODEL / "real_fixture_features.npy", allow_pickle=False)
    indices = provenance["fixtureTestIndices"]
    if features.shape != (len(indices), 8, 8, 5):
        raise ValueError("Frozen real-fixture shape mismatch")
    fixtures = list(model.quantize_inputs(features))
    fixtures += [np.zeros((8, 8, 5), dtype=np.int64), np.full((8, 8, 5), -128, dtype=np.int64),
                 np.full((8, 8, 5), 127, dtype=np.int64), np.where(np.arange(320).reshape(8, 8, 5) % 2, 127, -128)]
    fixtures += [fixtures[0].copy(), fixtures[0].copy()]
    inputs = np.stack(fixtures)
    trace = {}
    expected = model.forward_integer(inputs, trace)
    if not np.array_equal(expected[0], expected[-1]) or not np.array_equal(expected[0], expected[-2]):
        raise AssertionError("Reference frame reset failure")
    np.savez_compressed(GENERATED / "test_trace.npz", **trace)
    write_hex(GENERATED / "test_input.hex", inputs)
    write_hex(GENERATED / "test_expected.hex", expected)
    (GENERATED / "GeneratedTestConfig.bsv").write_text(
        "package GeneratedTestConfig;\n\ntypedef %d TestFrameCount;\n\n"
        "function String testInputPath();\n\treturn \"generated/test_input.hex\";\nendfunction\n\n"
        "function String testExpectedPath();\n\treturn \"generated/test_expected.hex\";\nendfunction\n\nendpackage\n" % len(fixtures))
    return {"count": len(fixtures), "realTestIndices": indices,
            "synthetic": ["zero", "all -128", "all +127", "alternating -128/+127", "repeat real index 0", "repeat real index 0"],
            "inputOrder": "320 signed INT8 HWC bytes/frame after model input preprocessing",
            "outputOrder": "57 signed INT8 x19,y19,z19 coordinates/frame",
            "inputExponent": model.exponent("input"), "outputExponent": model.exponent("output")}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, help="Optional MARS directory for full held-out evaluation")
    parser.add_argument("--batch-size", type=int, default=128)
    args = parser.parse_args()
    if args.batch_size < 1:
        parser.error("--batch-size must be positive")
    GENERATED.mkdir(parents=True, exist_ok=True)
    provenance = verify_model_bundle(EXPORT)
    tables, table_metadata = make_tables(EXPORT)
    np.save(GENERATED / "nonlinear_tables.npy", tables, allow_pickle=False)
    model = IntegerModel(EXPORT, tables)
    widths = hardware_width_checks(model)
    write_bsv(model)
    report = {"schemaVersion": 2, "architecture": "first baseline, combinational coefficient lookup",
              "exportManifestSHA256": file_hash(EXPORT / "manifest.json"),
              "quantizationSHA256": file_hash(EXPORT / "quantization.json"),
              "checkpointSHA256": file_hash(MODEL / "checkpoint.pt"),
              "modelProvenanceSHA256": file_hash(MODEL / "provenance.json"),
              "parameterCount": model.manifest["parameterCount"],
              "parameterVerification": "Every binary SHA256, size, shape, hex value and INT8 checkpoint tensor matched",
              "nonlinearROM": table_metadata, "hardwareWidthChecks": widths,
              "arithmeticChecks": arithmetic_checks(model),
              "normalization": "Exact rational (20*x-sum)*gamma/(20*(max-min))+beta, then one ties-even INT8 requantization; constant input returns requantized beta",
              "state": "INT24 current state; output before arithmetic right shift by 7 into INT17 retained state; reset per frame",
              "testTuning": False, "rtlScope": "This report evaluates the integer software reference. RTL verification is reported separately."}
    report["fixtures"] = write_fixtures(model, provenance)
    if args.data:
        features_path = args.data / "featuremap_test.npy"
        labels_path = args.data / "labels_test.npy"
        previous = json.loads((MODEL / "metrics.json").read_text())
        for path in [features_path, labels_path]:
            if file_hash(path) != previous["dataset_test_sha256"][path.name]:
                raise ValueError("Test dataset differs from frozen PTQ evaluation: " + str(path))
        features = np.asarray(np.load(features_path, allow_pickle=False), dtype=np.float32)
        labels = np.asarray(np.load(labels_path, allow_pickle=False), dtype=np.float32)
        if not np.array_equal(features[provenance["fixtureTestIndices"]], np.load(MODEL / "real_fixture_features.npy", allow_pickle=False)):
            raise ValueError("Frozen fixtures differ from original test data")
        started = time.perf_counter()
        predictions = []
        for start in range(0, len(features), args.batch_size):
            predictions.append(model.forward(features[start:start + args.batch_size]))
        predictions = np.concatenate(predictions)
        elapsed = time.perf_counter() - started
        physical = predictions.astype(np.float64) * 2.0 ** model.exponent("output")
        existing = np.load(MODEL / "predictions_int8_ptq.npy", allow_pickle=False)
        existing_int = np.rint(existing.astype(np.float64) / 2.0 ** model.exponent("output")).astype(np.int64)
        difference = predictions - existing_int
        report["fullTest"] = {"integerReference": metrics(physical, labels), "existingSwQDQ": metrics(existing, labels),
                              "evaluationSeconds": elapsed, "matchedOutputElements": int(np.count_nonzero(difference == 0)),
                              "totalOutputElements": int(difference.size), "matchedFrames": int(np.count_nonzero(np.all(difference == 0, axis=1))),
                              "maxOutputDifferenceLSB": int(np.abs(difference).max()), "meanAbsoluteOutputDifferenceLSB": float(np.abs(difference).mean()),
                              "differenceRMSE_cm": float(np.sqrt(np.mean((physical - existing) ** 2)) * 100.0),
                              "comparison": "Integer rational normalization replaces float32 QDQ normalization; no blanket bit-exact SW claim"}
        report["datasetSHA256"] = {path.name: file_hash(path) for path in [features_path, labels_path]}
        np.save(GENERATED / "predictions_integer.npy", predictions.astype(np.int8), allow_pickle=False)
    finalize_report(report)
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
